#%RAML 1.0
title: TWARecurting API
description:
version: V2
baseUri: http://api.bronzesword.com/

/users:
  get:
    queryParameters:
      field: string
      value: string
    responses:
      200:
        body:
          application/json:
            properties:
              uri: string
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                email: string
                mobilePhone: string

    /password:
      put:
        description: 修改用户密码
        body:
          application/json:
            properties:
              oldPassword: string
              password: string
        responses:
          200:
            body:
              application/json:
                properties:
                  uri: string
    /groups:
        get:
          description: 查看用户所有群组
          responses:
            200:
              body:
                application/json:
                  properties:
                    type[]:
                      properties:
                        id: integer
                        name: string
                        avatar: string

/groups:
  post:
    description: 创建群组
    body:
      application/json:
        properties:
          name: string
          avatar: string
          adminId: integer
          announcement: string
          isAnnouncePublished: boolean
    responses:
      201:
        body:
          application/json:
            properties:
              uri: string

  /{id}:
    get:
      description: 查看群组信息
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                name: string
                avatar: string
                announcement: string
                isAnnouncePublished: boolean
    put:
      description: 修改群组信息
      body:
        application/json:
          properties:
            avatar: string
            announcement: string
            isAnnouncePublished: boolean
      responses:
        200:
          body:
            application/json:
              properties:
                uri: string
    /papers:
      description: 查看群组的试卷列表
      get:
        responses:
          200:
            body:
              application/json:
                properties:
                  type[]:
                    properties:
                      id: integer
